chat/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [  
    path('', views.entrance, name="entrance"),
    path('index/', views.index, name="index"),
    path('chat_room/<int:pk>/', views.chat_room, name="chat_room"),

    path('index_exit/', views.index_exit, name="index_exit"),
    path('chat_room_exit/', views.chat_room_exit, name="chat_room_exit"),

    path('refresh/<int:pk>/', views.refresh, name="refresh"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("chat.urls")),
]

chat/models.py
from django.db import models
from django.utils import timezone

import uuid


class Room(models.Model):
    dt = models.DateField(verbose_name="投稿日時",default=timezone.now)
    room_name = models.CharField(verbose_name="ルーム名",max_length=100)

class Chat(models.Model):
    dt = models.DateTimeField(verbose_name="投稿日時",default=timezone.now)

    #ChatUserと1対多を組むと、ChatUserが消えた時、Chatの表示にも影響するため、ここには投稿当時のデータを記録する
    room = models.ForeignKey(Room,verbose_name="ルーム名",on_delete=models.CASCADE)
    name = models.CharField(verbose_name="投稿者名",max_length=100)

    #ipアドレスは投稿されるたびに記録する
    ip = models.GenericIPAddressField(verbose_name="IPアドレス")

    comment = models.TextField(verbose_name="原文コメント")
    ja_comment = models.TextField(verbose_name="日本語コメント")
    en_comment = models.TextField(verbose_name="英語コメント")
    zh_comment = models.TextField(verbose_name="中国語コメント")
    ko_comment = models.TextField(verbose_name="韓国語コメント")
    de_comment = models.TextField(verbose_name="ドイツ語コメント")
    fr_comment = models.TextField(verbose_name="フランス語コメント")


class ChatUser(models.Model):

    id          = models.UUIDField( default=uuid.uuid4, primary_key=True, editable=False )

    #Cookieに記録されていた名前とルームをChatUserに記録。Cookieには上記idのみを記録する
    name        = models.CharField(verbose_name="投稿者名",max_length=100)
    room        = models.ForeignKey(Room,verbose_name="ルーム名",on_delete=models.CASCADE,null=True,blank=True)

    language    = models.CharField(verbose_name="言語指定",max_length=10)

chat/forms.py
from django import forms
from .models import Chat, Room, ChatUser

"""
class RoomEnterForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ["name", "room"]



class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ["room_name"]

"""


class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ["comment","ip", "room", "name", "ja_comment", "en_comment", "zh_comment", "ko_comment", "de_comment", "fr_comment"]

class ChatBeforeForm(forms.ModelForm):
    class Meta:
        model = Chat
        #TODO:roomとnameとipがない
        fields = ["comment","ip", "room", "name",]




class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ["room_name"]

class RoomEnterForm(forms.ModelForm):
    class Meta:
        model = ChatUser
        fields = ["room"]

class ChatUserForm(forms.ModelForm):
    class Meta:
        model = ChatUser
        fields = ["name","room","language"]




#ロングポーリング用のフォームクラス
class ChatFirstForm(forms.Form):

    #Topicのidに基づく
    first = forms.IntegerField()

chat/views.py
import pkgutil
from django.shortcuts import render, redirect

from django.views import View

from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Chat, Room, ChatUser
from .forms import RoomEnterForm, ChatForm, ChatBeforeForm, RoomForm, ChatFirstForm, ChatUserForm

import urllib
import time

from googletrans import Translator


class EntranceView(View):

    def get(self, request, *args, **kwargs):

        #TODO:ここでCookieが存在する場合はChatUserを検索
        if "id" in request.COOKIES:

            #Cookieに記録されているChatUserのidを取得
            chat_user_id = urllib.parse.unquote(request.COOKIES["id"])
            chat_user    = ChatUser.objects.filter(id=chat_user_id).first()

            #roomの指定がある場合はroomへリダイレクト
            if chat_user.room:
                return redirect("chat:chat_room", chat_user.room.id)
            else:
                #部屋一覧のページへリダイレクト
                return redirect("chat:index")


        return render(request, "chat/entrance.html")

    def post(self, request, *args, **kwargs):

        form        = ChatUserForm(request.POST)

        if not form.is_valid():
            return redirect("chat:entrance")

        chat_user    = form.save()

        response    = redirect("chat:index")

        #TIPS:UUIDは文字列に直して格納する
        response.set_cookie("id", urllib.parse.quote(str(chat_user.id)))

        return response

entrance    = EntranceView.as_view()


class IndexView(View):
    def get(self, request, *args, **kwargs):
        #チャットのルーム選択。(ルーム一覧をcontextに入れる)
        context = {}
        context["rooms"] = Room.objects.order_by("-dt")

        return render(request, "chat/index.html", context)

    def post(self, request, *args, **kwargs):
        #ルームの新規作成
        room_form   = RoomForm(request.POST)



        #ChatUserの存在確認
        if "id" not in request.COOKIES:
            return redirect("chat:entrance")

        #Cookieに記録されているChatUserのidを取得
        chat_user_id = urllib.parse.unquote(request.COOKIES["id"])
        chat_user    = ChatUser.objects.filter(id=chat_user_id).first()

        if not chat_user:
            return redirect("chat:entrance")



        if room_form.is_valid():
            #ルーム新規作成
            room            = room_form.save()
            copied          = request.POST.copy()
            copied["room"]  = room.id

            form            = RoomEnterForm(copied, instance=chat_user)
        else:
            #既存ルームに入室

            form            = RoomEnterForm(request.POST, instance=chat_user)


        if not form.is_valid():
            print("RoomEnterFormのバリデーションエラー")
            return redirect("chat:index")

        #ChatUserにroomを記録
        chat_user    = form.save()

        #リダイレクトする
        return redirect("chat:chat_room", chat_user.room.id)

index = IndexView.as_view()



class ChatRoomView(View):
    def get(self, request, pk, *args, **kwargs):
      
        context = {}
        context["room"] = Room.objects.filter(id=pk).first()
        context["chats"] = Chat.objects.filter(room=pk).order_by("dt")

        if "id" not in request.COOKIES:
            return redirect("chat:entrance")
        
        return render(request, "chat/chat_room.html", context)

    
    def post(self, request, pk, *args, **kwargs):
        
        data = {"error": True}

        #ChatUserの存在確認
        if "id" not in request.COOKIES:
            return redirect("chat:entrance")

        #Cookieに記録されているChatUserのidを取得
        chat_user_id = urllib.parse.unquote(request.COOKIES["id"])
        chat_user    = ChatUser.objects.filter(id=chat_user_id).first()

        if not chat_user:
            return redirect("chat:entrance")


        #(リバース)プロキシサーバー有りと想定してIPアドレスのリストを取得
        ip_list = request.META.get('HTTP_X_FORWARDED_FOR')
        if ip_list:
            ip  = ip_list.split(',')[0]#そのうちの最初のIPアドレス(クライアントのグローバルIPアドレス)
        else:
            ip  = request.META.get('REMOTE_ADDR')#このサーバーに直接アクセスしてきたIPアドレスを取得

        copied          = request.POST.copy()
        copied["ip"]    = ip
        copied["room"]  = pk
        copied["name"]  = chat_user.name

        form = ChatBeforeForm(copied)

        if not form.is_valid():
            print(form.errors)
            print("form.is_valid()失敗1")
            return JsonResponse(data)

        cleaned = form.clean()
        comment = cleaned["comment"]
         
        # copied = request.POST.copy()
        translator = Translator()
        copied["ja_comment"] = translator.translate(comment, dest="ja").text
        copied["en_comment"] = translator.translate(comment, dest="en").text
        copied["zh_comment"] = translator.translate(comment, dest="zh-CN").text
        copied["ko_comment"] = translator.translate(comment, dest="ko").text
        copied["de_comment"] = translator.translate(comment, dest="de").text
        copied["fr_comment"] = translator.translate(comment, dest="fr").text

        form = ChatForm(copied)
        if not form.is_valid():
            print(form.errors)
            print("form.is_valid()失敗2")
            return JsonResponse(data)

        form.save()

        context = {}
        context["chats"] = Chat.objects.filter(room=pk).order_by("dt")

        data["error"] = False
        #render_to_stringはレンダリング結果を文字列にして返す
        data["content"] = render_to_string("chat/content.html", context, request)

        return JsonResponse(data)

chat_room = ChatRoomView.as_view()


class IndexExitView(View):
    def post(self, request, *args, **kwargs):

        if "id" not in request.COOKIES:
            return redirect("chat:entrance")

        #Cookieに記録されているChatUserのidを取得
        chat_user_id = urllib.parse.unquote(request.COOKIES["id"])
        chat_user    = ChatUser.objects.filter(id=chat_user_id).first()

        if not chat_user:
            return redirect("chat:entrance")

        #ChatUserを削除する
        chat_user.delete()

        response    = redirect("chat:entrance")
        response.delete_cookie("id")

        return response

index_exit  = IndexExitView.as_view()



class ChatRoomExitView(View):
    def post(self, request, *args, **kwargs):

        if "id" not in request.COOKIES:
            return redirect("chat:entrance")

        #Cookieに記録されているChatUserのidを取得
        chat_user_id = urllib.parse.unquote(request.COOKIES["id"])
        chat_user    = ChatUser.objects.filter(id=chat_user_id).first()

        if not chat_user:
            return redirect("chat:entrance")



        #roomを削除する
        chat_user.room  = None
        chat_user.save()

        return redirect("chat:index")

chat_room_exit  = ChatRoomExitView.as_view()




class RefreshView(View):
    def get(self, request, pk, *args, **kwargs):
        data = {"error": True}

        context = {}


        # 送信されたIDを抜き取り、最新データのチェックで扱えるようにする。
        form = ChatFirstForm(request.GET)

        first = None
        if form.is_valid():
            cleaned = form.clean()
            first = cleaned["first"]
        else:
            print(form.errors)
        

        for i in range(30):

            time.sleep(1)
            chat = Chat.objects.order_by("-dt").first()

            #以降はtopicが存在することを前提とするため、存在しない場合は次のループへ(エラー回避)
            if not chat:
                continue 

            #トピックが存在し、なおかつ送られたファーストデータは空。
            if not first:
                break

            #トピックのidと送られたファーストデータが異なる
            if chat.id != first:
                break

        #order_by("-dt")で新しい物が上、order_by("dt")で新しい物が下 
        context["chats"] = Chat.objects.filter(room=pk).order_by("dt")

        data["error"] = False
        data["content"] = render_to_string("chat/content.html", context, request)

        return JsonResponse(data)

refresh = RefreshView.as_view()

templates/chat/chat_room.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>global_chat_room</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script>
        const THIS_URL = '{% url "chat:chat_room" room.id %}';
        const REFRESH_URL = '{% url "chat:refresh" room.id %}';
    </script>
    
    {# ajax送信前にCSRFトークンをセットするコード #}
    <script src="{% static 'chat/js/ajax.js' %}"></script>
    {# ajaxを送信するコード #}
    <script src="{% static 'chat/js/chat_room.js' %}"></script>

    <link rel="stylesheet" href="{% static 'chat/css/chat_room.css' %}">

</head>
<body>
    <main class="container">



        <h1>{{ room.name }}</h1>
        
        <div id="content_area">
            {% include "chat/content.html" %}
        </div>


        <form id="form_area" action="" method="POST">
            {% csrf_token %}
            <textarea id="textarea" class="form-control" name="comment"></textarea>
            <input id="submit" type="button" value="送信">
        </form>

        <form action="{% url 'chat:chat_room_exit' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="退室">
        </form>
        
    </main>
</body>
</html>

templates/chat/content.html
{% load custom_tag %}

{% for chat in chats %}

{% if forloop.last %}
<input id="first" type="hidden" value="{{ chat.id }}" name="first">
{% endif %}


<div class="border">
    <div>
        <div>name:{{ chat.name }}</div>
        <div>{{ chat.dt }}</div>
        <div>{{ chat.ip }}</div>

        <div>{{ chat.comment }}</div>

        {% same_name_check chat.name request.COOKIES.name request.COOKIES.language chat %}
     
    </div>
</div>

{% empty %}
<input id="first" type="hidden" value="" name="first">

{% endfor %}

templates/chat/entrance.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>global_chat</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>
<body>

    <h1 class="bg-primary text-white">チャットサイト</h1>
    <main class="container">

        <form action="" method="POST">
            {% csrf_token %}
            名前：<input type="text" name="name" placeholder="名前を入力"><br>
            使用言語：<select name="language">
                <option name="language" value="Japanese">日本語</option>
                <option name="language" value="English">English</option>
                <option name="language" value="Chinese">中文</option>
                <option name="language" value="Korean">한국어</option>
                <option name="language" value="German">Deutsch</option>
                <option name="language" value="French">Français</option>
            </select><br>
            <input id="submit" type="submit" value="参加">
        </form>
        
    </main>
</body>
</html>

templates/chat/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>global_chat</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>
<body>

    <h1 class="bg-primary text-white">チャットサイト</h1>
    <main class="container">

        <h2>部屋を作る</h2>
        <form class="my-2" action="" method="POST">
            {% csrf_token %}
            部屋名：<input type="text" name="room_name" placeholder="部屋名を入力"><br>
            <input id="submit" type="submit" value="入室">
        </form>


        <h2>部屋に入る</h2>
        <form id="form_area" class="my-2" action="" method="POST">
            {% csrf_token %}
            部屋選択：
            <select name="room">
                {% for room in rooms %}
                <option value="{{ room.id }}">{{ room.room_name }}</option>
                {% endfor %}
            </select>
            <br>
            <input id="submit" type="submit" value="入室">
        </form>


        <form action="{% url 'chat:index_exit' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="終了">
        </form>
        
    </main>
</body>
</html>

templates/chat/translation.html
{% if language == "Japanese" %}
<div>{{ language }}:{{ chat.ja_comment }}</div>
{% elif language == "English" %}
<div>{{ language }}:{{ chat.en_comment }}</div>
{% elif language == "Chinese" %}
<div>{{ language }}:{{ chat.zh_comment }}</div>
{% elif language == "Korean" %}
<div>{{ language }}:{{ chat.ko_comment }}</div>
{% elif language == "German" %}
<div>{{ language }}:{{ chat.de_comment }}</div>
{% elif language == "French" %}
<div>{{ language }}:{{ chat.fr_comment }}</div>
{% endif %}